[conduit]
server ansible_host=74.248.155.190 ansible_user=azureuser

[conduit:vars]
repo_url=https://github.com/Umarbek-commits/devsecops-conduit.git
site_name=conduit.umarbek1202400.dpdns.org
ansible_ssh_common_args=-o UserKnownHostsFile=deploy/known_hosts -o StrictHostKeyChecking=yes
